Repository kubernetes-sigs/boskos, pull requests merged in 2020-12, with the labels that each got.

#54 Fix configsync for static -> dynamic -> static
  cmd/boskos/boskos.go
  ranch/ranch.go
  ranch/ranch_test.go
  ranch/storage.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/L

#56 Restore in-memory mode
  cmd/boskos/boskos.go
  crds/client.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/M

#57 Update to go1.15.6
  Makefile
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#61 boskos: serve health endpoints on the specified port
  cleaner/cleaner_test.go
  cleaner/v2/cleaner.go
  cleaner/v2/cleaner_test.go
  cmd/boskos/boskos.go
  cmd/cleaner/main.go
  crds/client.go
  go.mod
  go.sum
  handlers/handlers_test.go
  handlers/server_client_test.go
  mason/mason_test.go
  ranch/ranch_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XXL

#62 Don't add configsyncreconciler twice to manager
  cmd/boskos/boskos.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#63 Validate that resources are either static or dynamic
  common/config.go
  common/config_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/S

#64 OWNERS_ALIASES: Swap out aws-janitor contributors
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS
