Repository kubernetes-sigs/boskos, pull requests merged in 2020-11, with the labels that each got.

#47 aws-janitor: add --dry-run functionality
  aws-janitor/resources/addresses.go
  aws-janitor/resources/asg.go
  aws-janitor/resources/clean.go
  aws-janitor/resources/cloud_formation_stacks.go
  aws-janitor/resources/dhcp_options.go
  aws-janitor/resources/elb.go
  aws-janitor/resources/elbv2.go
  aws-janitor/resources/iam_instance_profiles.go
  aws-janitor/resources/iam_roles.go
  aws-janitor/resources/instance.go
  aws-janitor/resources/internet_gateways.go
  aws-janitor/resources/launch_configs.go
  aws-janitor/resources/launch_templates.go
  aws-janitor/resources/list.go
  aws-janitor/resources/nat_gateway.go
  aws-janitor/resources/network_interface.go
  aws-janitor/resources/route53.go
  aws-janitor/resources/route_tables.go
  aws-janitor/resources/security_groups.go
  aws-janitor/resources/set.go
  aws-janitor/resources/subnets.go
  aws-janitor/resources/volumes.go
  aws-janitor/resources/vpcs.go
  cmd/aws-janitor-boskos/main.go
  cmd/aws-janitor/main.go
  cmd/aws-resources-list/main.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XL

#48 aws-janitor: validate region flag
  aws-janitor/regions/regions.go
  aws-janitor/resources/clean.go
  cmd/aws-janitor/main.go
  cmd/aws-resources-list/main.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/M

#49 Update to go 1.15.5
  Makefile
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#50 Reaper: Cleanup logging
  cmd/reaper/reaper.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/S

#51 Mark and sweep elastic file systems
  aws-janitor/resources/efs.go
  aws-janitor/resources/list.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/testing, size/L

#52 Mark and sweep EBS volume snapshots
  aws-janitor/resources/list.go
  aws-janitor/resources/snapshots.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/testing, size/L

#46 GCP Janitor also cleans up pubsub resources
  cmd/janitor/gcp_janitor.py
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS
