Repository kubernetes-sigs/boskos, pull requests merged in 2020-10, with the labels that each got.

#40 Expose metric boskos_acquire_duration_seconds
  .gitignore
  cleaner/cleaner_test.go
  handlers/handlers.go
  mason/mason_test.go
  ranch/priority.go
  ranch/ranch.go
  ranch/ranch_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/testing, size/L

#41 Update to go 1.15.2 and alpine 3.12
  Makefile
  images/boskosctl/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#44 Improve config validation and add checkconfig cmd
  cmd/checkconfig/main.go
  common/config.go
  common/config_test.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/L

#45 Build checkconfig image
  images/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#43 support boskos resource of type image-builder-aws-account
  cmd/aws-janitor-boskos/main.go
  common/aws/common.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/testing, size/M
