Repository kubernetes-sigs/boskos, pull requests merged in 2020-05, with the labels that each got.

#4 Add verification and testing targets for CI
  .gitignore
  .golangci.yml
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify/boilerplate/boilerplate.Dockerfile.txt
  hack/verify/boilerplate/boilerplate.Makefile.txt
  hack/verify/boilerplate/boilerplate.bzl.txt
  hack/verify/boilerplate/boilerplate.go.txt
  hack/verify/boilerplate/boilerplate.py.txt
  hack/verify/boilerplate/boilerplate.sh.txt
  hack/verify/verify_boilerplate.py
  hack/verify/verify_modules.sh
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XL

#5 verify_boilerplate: don't require python3
  hack/verify/verify_boilerplate.py
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#6 Fix verify_boilerplate to work in python2
  hack/verify/verify_boilerplate.py
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#7 Fix broken links in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/testing, size/S

#8 Build images without bazel
  .dockerignore
  .gitignore
  BUILD.bazel
  Makefile
  aws-janitor/Dockerfile
  aws-janitor/cmd/aws-janitor-boskos/Makefile
  cmd/boskosctl/BUILD.bazel
  cmd/boskosctl/README.md
  cmd/boskosctl/boskosctl.go
  cmd/boskosctl/boskosctl_test.go
  hack/ensure-go.sh
  images/boskosctl/Dockerfile
  images/build.sh
  images/cloudbuild.yaml
  images/default/Dockerfile
  images/janitor/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/L

#10 Remove Bazel support
  .bazelrc
  BUILD.bazel
  Makefile
  WORKSPACE
  aws-janitor/BUILD.bazel
  aws-janitor/account/BUILD.bazel
  aws-janitor/cmd/aws-janitor-boskos/BUILD.bazel
  aws-janitor/cmd/aws-resources-list/BUILD.bazel
  aws-janitor/regions/BUILD.bazel
  aws-janitor/resources/BUILD.bazel
  aws-janitor/s3/BUILD.bazel
  cleaner/BUILD.bazel
  cleaner/v2/BUILD.bazel
  client/BUILD.bazel
  cmd/boskos/BUILD.bazel
  cmd/boskosctl/BUILD.bazel
  cmd/cleaner/BUILD.bazel
  cmd/fake-mason/BUILD.bazel
  cmd/janitor/BUILD.bazel
  cmd/metrics/BUILD.bazel
  cmd/reaper/BUILD.bazel
  common/BUILD.bazel
  common/aws/BUILD.bazel
  crds/BUILD.bazel
  hack/print-workspace-status.sh
  handlers/BUILD.bazel
  mason/BUILD.bazel
  metrics/BUILD.bazel
  push.sh
  ranch/BUILD.bazel
  repositories.bzl
  storage/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XXL

#11 aws-janitor: clean up elbv2 resources
  aws-janitor/resources/elb.go
  aws-janitor/resources/elbv2.go
  aws-janitor/resources/list.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/L

#9 Switch to gcr.io/k8s-staging-boskos
  Makefile
  images/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/M
