Repository kubernetes-sigs/boskos, pull requests merged in 2021-03, with the labels that each got.

#70 aws-janitor: support filtering based on tags
  aws-janitor/resources/addresses.go
  aws-janitor/resources/asg.go
  aws-janitor/resources/clean.go
  aws-janitor/resources/cloud_formation_stacks.go
  aws-janitor/resources/dhcp_options.go
  aws-janitor/resources/efs.go
  aws-janitor/resources/eks.go
  aws-janitor/resources/elb.go
  aws-janitor/resources/elbv2.go
  aws-janitor/resources/iam_instance_profiles.go
  aws-janitor/resources/iam_roles.go
  aws-janitor/resources/instance.go
  aws-janitor/resources/internet_gateways.go
  aws-janitor/resources/launch_configs.go
  aws-janitor/resources/launch_templates.go
  aws-janitor/resources/list.go
  aws-janitor/resources/nat_gateway.go
  aws-janitor/resources/network_interface.go
  aws-janitor/resources/route53.go
  aws-janitor/resources/route_tables.go
  aws-janitor/resources/security_groups.go
  aws-janitor/resources/set.go
  aws-janitor/resources/set_test.go
  aws-janitor/resources/snapshots.go
  aws-janitor/resources/sqs.go
  aws-janitor/resources/subnets.go
  aws-janitor/resources/tags.go
  aws-janitor/resources/tags_test.go
  aws-janitor/resources/volumes.go
  aws-janitor/resources/vpcs.go
  cmd/aws-janitor-boskos/main.go
  cmd/aws-janitor/main.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XXL

#75 aws-janitor-boskos: add clean time and process time metrics
  cmd/aws-janitor-boskos/main.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/M

#76 dependencies: update several dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/L

#78 aws-janitor: add job duration metric
  cmd/aws-janitor/main.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/L

#77 aws-janitor: manage all IAM roles except system roles
  aws-janitor/resources/iam_instance_profiles.go
  aws-janitor/resources/iam_roles.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/M
