Repository kubernetes-sigs/boskos, pull requests merged in 2021-02, with the labels that each got.

#67 aws-janitor: normalize generated arn ids for resources
  aws-janitor/resources/asg.go
  aws-janitor/resources/cloud_formation_stacks.go
  aws-janitor/resources/efs.go
  aws-janitor/resources/elb.go
  aws-janitor/resources/launch_configs.go
  aws-janitor/resources/route53.go
  aws-janitor/resources/snapshots.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/L

#69 aws-janitor: Cleanup SQS queues and EventBridge rules
  aws-janitor/resources/list.go
  aws-janitor/resources/sqs.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/L

#71 Update to go1.15.8
  Makefile
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#72 client: expose NewClientWithPasswordGetter
  client/client.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, sig/testing, size/S

#74 aws-janitor: fix ARN for snapshots and CFS
  aws-janitor/resources/cloud_formation_stacks.go
  aws-janitor/resources/snapshots.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/S
