Repository kubernetes-sigs/boskos, pull requests merged in 2021-08, with the labels that each got.

#93 Generate DeepCopy methods for CRD types
  Makefile
  common/common.go
  crds/client.go
  crds/doc.go
  crds/drlc_crd.go
  crds/resource_crd.go
  crds/zz_generated.deepcopy.go
  handlers/handlers.go
  handlers/handlers_test.go
  handlers/server_client_test.go
  handlers/testdata/testacquire-ok.golden
  ranch/priority.go
  ranch/priority_test.go
  ranch/ranch.go
  ranch/ranch_test.go
  ranch/storage.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XL, tide/merge-method-squash

#98 [GCP janitor] Update ZONES and use the new filter syntax
  cmd/janitor/gcp_janitor.py
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/S

#102 Update verify_boilerplate to python3
  hack/verify/verify_boilerplate.py
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/S

#101 Allow specifying additional zones for GCP janitor
  cmd/janitor/gcp_janitor.py
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/S

#99 Boskos: Allow HA by adding optional leader election
  cmd/boskos/boskos.go
  crds/client.go
  deployments/base/rbac.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, sig/testing
