Repository kubernetes-sigs/boskos, pull requests merged in 2022-09, with the labels that each got.

#149 drop require directives
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/S, ok-to-test

#146 Support vpc endpoints deletion in aws-janitor repo
  aws-janitor/resources/list.go
  aws-janitor/resources/vpc_endpoints.go
  cmd/aws-janitor-boskos/main.go
  cmd/aws-janitor/main.go
  cmd/aws-resources-list/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, sig/testing, ok-to-test

#121 AWS Janitor: Clean up IAM OIDC Provider resources also
  aws-janitor/resources/iam_oidc_providers.go
  aws-janitor/resources/list.go
Labels: cncf-cla: yes, lgtm, size/L, lifecycle/stale, approved, sig/testing
