Repository kubernetes-sigs/boskos, pull requests merged in 2022-08, with the labels that each got.

#143 Update IBM Cloud janitor dependencies
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, sig/testing

#144 Make GCP janitor thread-safe
  cmd/janitor/gcp_janitor.py
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, sig/testing, size/S

#145 Delete outdated key pairs in aws-janitor repo
  aws-janitor/resources/key_pairs.go
  aws-janitor/resources/list.go
  cmd/aws-janitor-boskos/main.go
  cmd/aws-janitor/main.go
  cmd/aws-resources-list/main.go
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, sig/testing, ok-to-test

#147 Update README.md
  README.md
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS
