Repository kubernetes-sigs/boskos, pull requests merged in 2022-07, with the labels that each got.

#128 Make test and verify work under go-lang version >=1.17
  Makefile
  crds/zz_generated.deepcopy.go
  hack/go_install.sh
  hack/verify/verify_boilerplate.py
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/S, ok-to-test

#133 aws-janitor: Use the creation time if it is specified
  aws-janitor/resources/set.go
  aws-janitor/resources/set_test.go
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/S

#134 Distinguish between resources busy and unknown resource type
  client/client.go
  client/client_test.go
  common/common.go
  ranch/ranch.go
Labels: cncf-cla: yes, lgtm, size/L, approved, sig/testing, ok-to-test

#131 Bump test infra dependency
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XL, sig/testing

#137 Update test-infra dep to latest
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XL, sig/testing

#136 Support target groups deletion in aws-janitor repo.
  aws-janitor/resources/list.go
  aws-janitor/resources/target_groups.go
  cmd/aws-janitor-boskos/main.go
  cmd/aws-janitor/main.go
  cmd/aws-resources-list/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, sig/testing, ok-to-test

#138 Revert "Merge pull request #137 from olemarkus/update-test-infra"
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XL, sig/testing

#139 Bump default golang version used by make targets
  Makefile
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS

#140 Bump alpine version used for the boskosctl image
  images/boskosctl/Dockerfile
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS

#141 Revert "Revert "Merge pull request #137 from olemarkus/update-test-infra
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XL, sig/testing
