Repository kubernetes-sigs/boskos, pull requests merged in 2024-02, with the labels that each got.

#186 Boskos janitor: bump gcloud version to latest and run go mod tidy.
  Makefile
  go.mod
  go.sum
  images/janitor/Dockerfile
Labels: cncf-cla: yes, lgtm, size/M, approved, sig/testing, ok-to-test

#183 ssl-policies should be cleaned up after target-https-proxies.
  cmd/janitor/gcp_janitor.py
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, sig/testing, size/XS

#184 Update dependencies
  Makefile
  crds/zz_generated.deepcopy.go
  hack/verify/verify_boilerplate.py
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS, ok-to-test

#188 Add krzyzacy@ back to OWNERS
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS

#187 Bump alpine_version in boskosctl image to 3.17.
  images/boskosctl/Dockerfile
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, sig/testing, size/XS

#182 Cleanup OIDC providers created by eksctl for `ci-shared-aws`
  aws-janitor/resources/iam_oidc_providers.go
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS
