Repository kubernetes-sigs/boskos, pull requests merged in 2024-07, with the labels that each got.

#193 Updated gcp_janitor.py to clean secret manager resources
  cmd/janitor/gcp_janitor.py
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS, ok-to-test

#194 [gcp_janitor.py] Add removal of internal-ranges
  cmd/janitor/gcp_janitor.py
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS, ok-to-test

#195 Add Parallelstore instance support to GCP Janitor
  cmd/janitor/gcp_janitor.py
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, sig/testing, size/S

#197 Move from AWS SDK v1 to v2
  Makefile
  aws-janitor/account/account.go
  aws-janitor/regions/regions.go
  aws-janitor/resources/addresses.go
  aws-janitor/resources/asg.go
  aws-janitor/resources/clean.go
  aws-janitor/resources/cloud_formation_stacks.go
  aws-janitor/resources/dhcp_options.go
  aws-janitor/resources/efs.go
  aws-janitor/resources/eks.go
  aws-janitor/resources/elb.go
  aws-janitor/resources/elbv2.go
  aws-janitor/resources/iam_instance_profiles.go
  aws-janitor/resources/iam_oidc_providers.go
  aws-janitor/resources/iam_roles.go
  aws-janitor/resources/instance.go
  aws-janitor/resources/internet_gateways.go
  aws-janitor/resources/key_pairs.go
  aws-janitor/resources/launch_configs.go
  aws-janitor/resources/launch_templates.go
  aws-janitor/resources/list.go
  aws-janitor/resources/nat_gateway.go
  aws-janitor/resources/network_interface.go
  aws-janitor/resources/route53.go
  aws-janitor/resources/route53_test.go
  aws-janitor/resources/route_tables.go
  aws-janitor/resources/s3_bucket.go
  aws-janitor/resources/security_groups.go
  aws-janitor/resources/set.go
  aws-janitor/resources/snapshots.go
  aws-janitor/resources/sqs.go
  aws-janitor/resources/subnets.go
  aws-janitor/resources/tags.go
  aws-janitor/resources/tags_test.go
  aws-janitor/resources/target_groups.go
  aws-janitor/resources/volumes.go
  aws-janitor/resources/vpc_endpoints.go
  aws-janitor/resources/vpcs.go
  aws-janitor/s3/s3.go
  cmd/aws-janitor-boskos/main.go
  cmd/aws-janitor/main.go
  cmd/aws-resources-list/main.go
  common/aws/common.go
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XXL, approved, sig/testing

#198 sync aliases from k/test-infra
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/S

#199 Bump Go and Alpine versions
  Makefile
  images/boskosctl/Dockerfile
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS
