Repository kubernetes-sigs/boskos, pull requests merged in 2025-05, with the labels that each got.

#228 Update verify and test tool versions in Makefile
  Makefile
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS

#226 Janitor Cleanup Based on VPC ID
  common/ibmcloud/common.go
  internal/ibmcloud-janitor/resources/vpc.go
  internal/ibmcloud-janitor/resources/vpc_client.go
  internal/ibmcloud-janitor/resources/vpc_instances.go
  internal/ibmcloud-janitor/resources/vpc_lbs.go
  internal/ibmcloud-janitor/resources/vpc_networks.go
Labels: cncf-cla: yes, lgtm, size/L, approved, sig/testing, ok-to-test

#222 Build and push multi-arch images for platform s390x
  Makefile
  images/build.sh
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS, ok-to-test

#227 Add a feature to skip cleanup for resources of type powervs
  cmd/ibmcloud-janitor-boskos/main.go
  go.mod
  go.sum
  internal/ibmcloud-janitor/resources/clean.go
  internal/ibmcloud-janitor/resources/powervs_client.go
  internal/ibmcloud-janitor/resources/powervs_workspaces.go
  internal/ibmcloud-janitor/resources/tagging.go
Labels: cncf-cla: yes, lgtm, size/L, approved, sig/testing

#229 Increase timeout for image build
  images/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, approved, sig/testing, size/XS
